server:
  port: 8081 # 포트 중복 충돌 방지

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    # 💡 결제 완료 후 최종 토픽 발행을 위한 고신뢰 프로듀서 설정
    producer:
      acks: all # min.insync.replicas=2
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true # 멱등성 프로듀서 활성화 (중복 전송 차단)
        max.in.flight.requests.per.connection: 5


    consumer:
      group-id: ticket-payment-group
      auto-offset-reset: latest

      # 1. ErrorHandlingDeserializer를 래퍼(Wrapper)로 설정
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      # max.poll 관련 장애 연출 설정 유지
      max.poll.interval.ms: 10000
      max.poll.records: 50
      session.timeout.ms: 45000
      heartbeat.interval.ms: 15000

      properties:
        # 2. 실제 사용할 내부 Deserializer 지정
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        # 3. JSON 역직렬화 허용 패키지 및 DTO 지정
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.example.dto.TicketReservationDto

    listener:
      type: batch

  elasticsearch:
    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379