plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    // Java 17 툴체인 명시 (컴파일러 및 언어 레벨 고정)
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // 1. 스프링 웹 (Producer에서 REST API 만들 때 필요)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // 2. 스프링 카프카 (핵심 연동 라이브러리)
    implementation 'org.springframework.kafka:spring-kafka'

    // 3. Spring Data Elasticsearch
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'

    // 4. 롬복 (Lombok)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 테스트 의존성
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}